version: "3"
services:
  app_8081:
    container_name: app_8081
    build: .
    environment:
      active.profile: "dev1"
      jwt.key: ${jwt_key}
      kobis.key: ${kobis_key}
      quartz.time: "0 51 00 * * ?"
      kmdb.key: ${kmdb_key}
      jwt.time: "86400"
      jdbc.url: ${jdbc_url}
      db.name: "rere"
      db.password: ${db_password}
      SPRING_DATASOURCE_USERNAME: root
    restart: always
    ports:
      - "8081:8081"

  app_8082:
    container_name: app_8082
    build: .
    environment:
      active.profile: "dev2"
      jwt.key: ${jwt_key}
      kobis.key: ${kobis_key}
      quartz.time: "0 51 00 * * ?"
      kmdb.key: ${kmdb_key}
      jwt.time: "86400"
      jdbc.url: ${jdbc_url}
      db.name: "rere"
      db.password: ${db_password}
      SPRING_DATASOURCE_USERNAME: root
    restart: always
    ports:
      - "8082:8082"

  redis:
    image: redis:alpine
    container_name: composeRedis
    restart: always
    ports:
      - "6379:6379"