spring:
  profiles:
    active: ${active.profile}
    group:
      "local1": "local1, common"
      "local2": "local2, common"
      "dev1": "dev1, common"
      "dev2": "dev2, common"
---
spring:
  config:
    activate:
      on-profile: common
  messages:
    basename: errors
    encoding: UTF-8
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        jdbc.batch_size: 1000
        default_batch_fetch_size: 1000
#        show_sql: true
        format_sql: true
  batch:
    job:
      enabled: false
      firstPage: ${batch.job.firstPage}

logging:
  file:
    path: /var/log/app1/
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
    io.swagger.models.parameters.AbstractSerializableParameter: error

jwt:
  header: Authorization
  secret: ${jwt.key}
  token-validity-in-seconds: ${jwt.time}

api:
  kobis_secret: ${kobis.key}
  kmdb_sercret: ${kmdb.key}

quartz:
  config: ${quartz.time}

springfox:
  documentation:
    swagger:
        use-model-v3: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: local1
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local2
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded
server:
  port: 8082
---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  config:
    activate:
      on-profile: dev1
  datasource:
    hikari:
      jdbc-url: ${jdbc.url}
      username: ${db.name}
      password: ${db.password}
      driver-class-name: org.mariadb.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: never
server:
  port: 8081
---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  config:
    activate:
      on-profile: dev2
  datasource:
    hikari:
      jdbc-url: ${jdbc.url}
      username: ${db.name}
      password: ${db.password}
      driver-class-name: org.mariadb.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: never
server:
  port: 8082
---