spring:
  profiles:
    active: dev
    group:
      "local": "local, common"
      "dev": "dev, common"
---
spring:
  config:
    activate:
      on-profile: common
  messages:
    basename: errors
    encoding: UTF-8
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        jdbc.batch_size: 1000
        default_batch_fetch_size: 1000
#        show_sql: true
#        format_sql: true
  batch:
    job:
      enabled: false

logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
  io.swagger.models.parameters.AbstractSerializableParameter: error

jwt:
  header: Authorization
  secret: ${jwt.key}
  token-validity-in-seconds: 86400

api:
  secret: ${api.key}

quartz:
  config: ${quartz.time}

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded
---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/movierank?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
      username: yhw
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
---