spring:
  profiles:
    active: local
    group:
      "local": "local, common"
      "dev": "dev, common"
---
spring:
  config:
    activate:
      on-profile: common
  messages:
    basename: errors
    encoding: UTF-8
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        jdbc.batch_size: 1000
        default_batch_fetch_size: 1000
        #show_sql: true
        format_sql: true
  batch:
    jdbc:
      initialize-schema: embedded

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  header: Authorization
  secret: ${secret.key}
  token-validity-in-seconds: 86400
api:
  secret: ${api.key}
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: mariadb
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/movierank?characterEncoding=UTF-8&serverTimezone=UTC
      username: yhw
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver
---

